### PR TITLE
Adjust Biomes! Caverns integration so it produces actual cavern maps

### PR DESCRIPTION
**Pull request by m00nl1ght-dev**
Also fixes a performance issue in the harmony patch for map.Biome
(looking up the biome by name every time any code calls map.Biome is very costly)

### CODE REVIEW

**Comment by emipa606** [comment]
Needs more work, when testing this made above-ground maps since there are no mountain heightmap to use the vanilla map-gen with.

**Comment by m00nl1ght-dev** [comment]
Can you give an example map screenshot with that issue please? When I tested it produced caverns maps as expected.

Also, what do you mean by mountain heightmap? The `MapGenerator.Elevation` grid?

**Comment by emipa606** [comment]
I guess it could work if you started drilling from a cave as each map would use the Elevation grid from the original tile. Did you test drilling from a normal biome?

**Comment by m00nl1ght-dev** [comment]
Yes, I did test on a standard flat map. But that was before I rebased onto your latest commit [c7d0958](https://github.com/emipa606/DeepRim/commit/c7d0958c6de31ff614cb38d68f66a2a9c9459930).

That commit breaks the `map.Biome` patch. The method name is wrong and the harmony annotation is missing the `MethodType.Getter`. Unrelated to the changes in this PR, that causes the underground biomes to not appear, and instead the biome of the world tile is used.

I added a fix for it to this PR.
Edit: Apparently new changes don't appear when the PR is already closed. If you want I can open a new PR.

**Comment by emipa606** [comment]
If you could that would be great!

**Comment by m00nl1ght-dev** [comment]
Here it is: https://github.com/emipa606/DeepRim/pull/7

**Pull request merged**
